# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fedfl_pb2 as fedfl__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fedfl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederationServiceStub(object):
    """Service này được Server gọi và Client triển khai (Client là gRPC server)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinFederation = channel.unary_unary(
                '/FederationService/JoinFederation',
                request_serializer=fedfl__pb2.JoinRequest.SerializeToString,
                response_deserializer=fedfl__pb2.WeightsResponse.FromString,
                _registered_method=True)
        self.SendLocalUpdate = channel.unary_unary(
                '/FederationService/SendLocalUpdate',
                request_serializer=fedfl__pb2.LocalUpdateRequest.SerializeToString,
                response_deserializer=fedfl__pb2.WeightsResponse.FromString,
                _registered_method=True)


class FederationServiceServicer(object):
    """Service này được Server gọi và Client triển khai (Client là gRPC server)
    """

    def JoinFederation(self, request, context):
        """Client đăng ký và nhận global model lần đầu
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLocalUpdate(self, request, context):
        """Client gửi cập nhật local lên Server và nhận global model tiếp theo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinFederation': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinFederation,
                    request_deserializer=fedfl__pb2.JoinRequest.FromString,
                    response_serializer=fedfl__pb2.WeightsResponse.SerializeToString,
            ),
            'SendLocalUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLocalUpdate,
                    request_deserializer=fedfl__pb2.LocalUpdateRequest.FromString,
                    response_serializer=fedfl__pb2.WeightsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FederationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FederationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederationService(object):
    """Service này được Server gọi và Client triển khai (Client là gRPC server)
    """

    @staticmethod
    def JoinFederation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FederationService/JoinFederation',
            fedfl__pb2.JoinRequest.SerializeToString,
            fedfl__pb2.WeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLocalUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FederationService/SendLocalUpdate',
            fedfl__pb2.LocalUpdateRequest.SerializeToString,
            fedfl__pb2.WeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
